### ISSUE TITLE
Develop build infrastructure

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/oasis3-mct#1]
Develop spack based build infrastructure.

**Comment by harshula** [comment]
Draft Spack package file in commit https://github.com/ACCESS-NRI/spack_packages/commit/d2b0a47079ca6ad152618d444bd4540ada0557c6

**Comment by harshula** [comment]
The current Spack package file is: https://github.com/ACCESS-NRI/spack_packages/blob/main/packages/oasis3-mct/package.py

**Comment by harshula** [comment]
PR: https://github.com/ACCESS-NRI/spack_packages/pull/6
