### ISSUE TITLE
ACCESS-ESM1.5 version in repo

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/oasis3-mct#2]
Ideally want to use one version of OASIS3 in all models.

Need to have the version of OASIS3 used in ACCESS-ESM1.5 publicly accessible in GitHub repo

Need to

- identify code used
- use tool to export svn branch to git
- push to this repository
- establish if there are any significant differences with version in `master`

**Comment by penguian** [comment]
I have added two Pull Requests, #19 to compare with the `new_modules_pbd562` branch of `penguian/oasis3-mct`, and #20 to compare with the `new_modules` branch of `coecms/oasis3-mct`. The `new_modules_pbd562` branch of `penguian/oasis3-mct` is based on the `new_modules` branch of `coecms/oasis3-mct`, with 3 extra commits.

The `new_modules_pbd562` branch of `penguian/oasis3-mct`, when used in the build of the `build-all-using-oasis3-new-modules-pbd562` branch of `penguian/access-esm-build-gadi`, and run from the `pre-industrial` branch of `penguian/access-esm`, reproduces the output of the `pre-industrial` branch of `coecms/access-esm`, which latter uses pre-built binaries from  `/g/data/access/payu/access-esm/bin/coe/`

I would recommend that PR #19 be accepted, after proper scrutiny of the commits, so the the `access-esm1.5` branch of the code here also reproduces the output of the `pre-industrial` branch of `coecms/access-esm` when run with the appropriate [config.yaml](https://github.com/penguian/access-esm/blob/pre-industrial-using-oasis3-new-modules-pbd562/config.yaml) file.
