### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/oasis3-mct#22]
For any shared code infrastructure we should have some protections against directly pushing changes to the default branch, in this case`master`.

There don't appear to have any branch protection rules for `master`. 

There is now also a special branch [`access-esm1.5`](https://github.com/ACCESS-NRI/oasis3-mct/tree/access-esm1.5) that should be protected, as this contains an ACCESS-ESM1.5 specific version of the code that will be used in a released product.

**Comment by CodeGat** [comment]
Branch Protection rules added for `master` and `access-esm1.5` to be in line with existing repositories, including the need for signed commits
