### ISSUE TITLE
Compile complete list of build dependencies

### ISSUE THREAD

**Issue by echus** [ACCESS-NRI/oasis3-mct#7]

**Comment by harshula** [comment]
Should be in:
```
$ find -iname '*configure.ac*'
./lib/mct/configure.ac
./compile_oa3-mct/build/lib/mctdir/configure.ac
```
&
```
util/make_dir/make.nci
```

**Comment by harshula** [comment]
Forgot to mention, have a look at ./build.sh for the versions of the modules (dependencies) we require at the moment.

**Comment by aidanheerdegen** [comment]
I believe the dependencies that exist on NCI that we need to replicate on GitHub CI is in these module loads:

https://github.com/ACCESS-NRI/oasis3-mct/blob/master/build.sh#L12-L15

Specifically
```
intel-compiler/2019.5.281
netcdf/4.7.4
openmpi/4.0.2
```

For the case of the GitHub CI we're subbing in `gfortran`, and the netcdf fortran interface has to be built too.

However Intel has recently made their OneAPI suite free to use for academic purposes, so it is [feasible to use it on GitHub CI in the future](https://neelravi.com/post/oneapi-github-workflow/).

Or use Intel provided containers

https://github.com/intel/oneapi-containers

**Comment by harshula** [comment]
This isn't the final version, but you might find the oasis3-mct spack package file useful:
https://github.com/ACCESS-NRI/spack_packages/commit/d2b0a47079ca6ad152618d444bd4540ada0557c6
